repos:
  - repo: local
    hooks:
      - id: check
        name: Run make check
        entry: make check
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
